# 公共配置文件
# @author 
# @from
spring:
  application:
    name: springboot-backend-fileupload
  # 默认 dev 环境
  profiles:
    active: @spring.profiles.active@
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  cache:
    # 一般来说是不用配置的，Spring Cache 会根据依赖的包自行装配
    type: redis
  session:
    store-type: redis
