spring:
  session:
    store-type: redis
  # 数据库配置
  datasource:
    master:
      jdbc-url: jdbc:mysql://localhost:3306/my_db?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
    lovefinder:
      jdbc-url: jdbc:mysql://localhost:3306/lovefinder?serverTimezone=Asia/Shanghai
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  elasticsearch:
    uris: http://localhost:9200
    username:
    password:
  # Redis 配置 共享session使用，每个模块必备
  redis:
    host: localhost
    port: 6379
    timeout: 10000ms
    # Redis默认情况下有16个分片，这里配置具体使用的分片
    database: 1
    lettuce:
      pool:
        # 连接池最大连接数（使用负值表示没有限制） 默认 8
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认 -1
        max-wait: -1ms
        # 连接池中的最大空闲连接 默认 8
        max-idle: 8
        # 连接池中的最小空闲连接 默认 0
        min-idle: 0
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
server:
  address: 0.0.0.0
  port: 8104
  servlet:
    context-path: /api
    # cookie 30 天过期
    session:
      cookie:
#        name: SESSION  # Session Cookie 名称，所有模块必须一致
#        path: /api     # Session Cookie 路径，所有模块必须一致
        max-age: 2592000
#        http-only: true
#        same-site: lax
# 接口文档配置
knife4j:
  enable: true
  openapi:
    title: "elasticsearch接口文档"
    version: 1.0
    group:
      default:
        api-rule: package
        api-rule-resources:
          - com.xiaofei.springbootbackendelasticsearch.controller